name: Vercel Nextjs Module Livestream Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_NEXT_MODULE_LIVESTREAM_ID }}
on:
  push:
    branches:
      - main
    paths:
      - 'apps/nextjs-module-livestream/**'
jobs:
  job1:
    runs-on: ubuntu-latest

    outputs:
      my_output: ${{ steps.out1.outputs.my_output }}
      output_2: ${{ steps.out2.outputs.output_2  }}

    steps:
      - name: output one line
        id: out1
        run: echo 'my_output="Hello, world!"' >> $GITHUB_OUTPUT

      - name: output two line
        id: out2
        run: |
          echo 'output_2="Hello, chicago!"' >> $GITHUB_OUTPUT

  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: get all outputs from prior job
        run: |
          echo "The outputs are ${{ toJSON(needs.job1.outputs) }}"
          echo
          jobjson=$(echo "${{ toJSON(needs.job1.outputs) }}" )
          echo $jobjson | yq
          echo
          echo "my_output is $(echo $jobjson | yq .my_output)"
