name: Vercel Nextjs Module Livestream Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_NEXT_MODULE_LIVESTREAM_ID }}
on:
  push:
    branches:
      - main
    paths:
      - 'apps/nextjs-module-livestream/**'
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set VERCEL_PROJECT_ID_TWO Dynamically
        id: set_project_id
        run: |
          declare -A project_map=(
            ["apps/nextjs-module-livestream"]="${{ secrets.VERCEL_PROJECT_NEXT_MODULE_LIVESTREAM_ID }}"
            ["apps/nextjs-project-1"]="1"
            ["apps/nextjs-project-2"]="2"
          )

          echo "{{ project_map[apps/nextjs-module-livestream] }}"

          for file in ${{ steps.changed-files.outputs.changed_files }}; do
            echo "$file was changed"
            # if [[ "${file}" =~ ^apps/nextjs-module-livestream ]]; then
            #   echo "VERCEL_PROJECT_ID_TWO=${{ secrets.VERCEL_PROJECT_NEXT_MODULE_LIVESTREAM_ID }}" >> $GITHUB_ENV
            #   exit 0
            # fi
          done

          echo "No matching project found for the modified paths."
          exit 1
